version: '3.5'
services:

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: FAKE_ACCESS_KEY
      MINIO_SECRET_KEY: FAKE_SECRET_KEY
    ports:
      - "9000:9000"
    command:  "server /data"